### PR TITLE
Updated links in leaders corner

### PR DESCRIPTION
**Pull request by csrs**
This fixes issues #288 and #275.

### CODE REVIEW

**Review by Tjzabel — DISMISSED** [review]
Looks good to me for RITlug :+1:

**Comment by csrs** [comment]
@alexdor Do you know what the build errors are / is it vital that we fix them?

**Comment by alexdor** [comment]
@csrs I think it's because of npm failing to install the dependancies on Travis, netlify seems to deploy normally so it shouldn't be vital

**Comment by csrs** [comment]
> @csrs I think it's because of npm failing to install the dependancies on Travis, netlify seems to deploy normally so it shouldn't be vital

@alexdor So good to merge? Have you checked the other 3 PRs?

**Comment by csrs** [comment]
@mirdaki Can you check this change?

**Review by mirdaki — DISMISSED** [review]
Yes, looks good!

**Comment by alexdor** [comment]
> > @csrs I think it's because of npm failing to install the dependancies on Travis, netlify seems to deploy normally so it shouldn't be vital
> 
> @alexdor So good to merge? Have you checked the other 3 PRs?

@csrs The only one that can merge the pull requests is @bacharakis, that is why I've assigned them to him

**Review by alexdor — APPROVED** [review]

**Pull request merged**
